### ISSUE TITLE
[FEATURE REQUEST] Expand to UK airports

### ISSUE THREAD

**Issue by ChopsKingsland** [nmatsuda/viz1090#15]
Is there the possibility of including UK airports, such as Lydd (EGMD/LYX)?

**Comment by nmatsuda** [comment]
Hi, I don't plan on preparing an airport data loader for other countries since each aviation regulatory body will have a different way of publishing this data. I took a quick look at the CAA website for the UK just now to see if I could point you to the right source but didn't find it. I'll close this comment, but if you do happen to figure this out yourself please consider making a pull request to add the data loader - so far I haven't had anyone do that for other countries.

**Comment by ChopsKingsland** [comment]
Okey dokey, I’ll see what I can find. Is there any specific data format I’m looking for?

**Comment by nmatsuda** [comment]
the most compatible option would be an ArcGIS shapefile as described [here](https://enterprise.arcgis.com/en/portal/10.6/use/shapefiles.htm), but I'm not sure if other agencies would use the exact same format as the FAA in the US. If you run the getmap.sh script from this repository it will get you the US one and you can take a look at the format.

**Comment by ChopsKingsland** [comment]
I have managed to find airport runway coords/data on [ourairports.com](ourairports.com). I have sanitised and reformatted the data to be somewhat in the same format as that of the FAA data. I can't upload the csv into this issue, so it is on [filebin](https://filebin.net/3uytg5tfk7tbwa49)
